name: Build Windows EXE

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-build.txt
    
    - name: Build Windows executable
      run: python build.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AMI-Windows
        path: dist/AMI-Windows.zip
        retention-days: 7
    
    - name: Calculate SHA256
      shell: pwsh
      run: |
        $hash = Get-FileHash -Path dist/AMI-Windows.zip -Algorithm SHA256
        echo "SHA256: $($hash.Hash)" > dist/SHA256.txt
        cat dist/SHA256.txt
    
    - name: Upload SHA256
      uses: actions/upload-artifact@v4
      with:
        name: SHA256
        path: dist/SHA256.txt
